import type { Reward } from "./types";

export const mockRewards: Reward[] = [
  {
    id: "1",
    title: "1 Hour of Gaming",
    description: "Reward yourself with an hour of your favorite game",
    category: "entertainment",
    pointsCost: 15,
    icon: "🎮",
    available: true,
  },
  {
    id: "2",
    title: "Social Media Break",
    description: "Take a guilt-free social media break for 20 minutes",
    category: "social",
    pointsCost: 5,
    icon: "📱",
    available: true,
  },
  {
    id: "3",
    title: "Order Takeout",
    description: "Treat yourself to a meal delivery instead of cooking",
    category: "food",
    pointsCost: 25,
    icon: "🍔",
    available: true,
  },
  {
    id: "4",
    title: "Movie Night",
    description: "Enjoy a movie without feeling guilty about productivity",
    category: "entertainment",
    pointsCost: 20,
    icon: "🎬",
    available: true,
  },
  {
    id: "5",
    title: "Extended Gaming Session",
    description: "Reward yourself with 2 hours of gaming",
    category: "entertainment",
    pointsCost: 30,
    icon: "🎯",
    available: true,
  },
  {
    id: "6",
    title: "Skip a Chore",
    description: "Skip one household chore guilt-free",
    category: "self-care",
    pointsCost: 15,
    icon: "🧹",
    available: true,
  },
  {
    id: "7",
    title: "Dessert Treat",
    description: "Enjoy your favorite dessert without guilt",
    category: "food",
    pointsCost: 10,
    icon: "🍰",
    available: true,
  },
  {
    id: "8",
    title: "Netflix Binge",
    description: "Binge watch your favorite show for 2 hours",
    category: "entertainment",
    pointsCost: 20,
    icon: "📺",
    available: true,
  },
  {
    id: "9",
    title: "Sleep In",
    description: "Sleep in an extra hour tomorrow morning",
    category: "self-care",
    pointsCost: 15,
    icon: "😴",
    available: true,
  },
  {
    id: "10",
    title: "Friend Hangout",
    description: "Schedule time with friends without productivity guilt",
    category: "social",
    pointsCost: 20,
    icon: "👥",
    available: true,
  },
];
