import type { Quest } from "./types";

export const mockQuests: Quest[] = [
  {
    id: "1",
    title: "Morning Meditation",
    description: "Start your day with a 10-minute meditation session",
    category: "mindfulness",
    difficulty: "easy",
    xpReward: 20,
    pointsReward: 10,
    estimatedTime: 10,
    createdBy: "system",
  },
  {
    id: "2",
    title: "Plan Your Day",
    description: "Create a to-do list for today's tasks",
    category: "productivity",
    difficulty: "easy",
    xpReward: 15,
    pointsReward: 8,
    estimatedTime: 5,
    createdBy: "system",
  },
  {
    id: "3",
    title: "30-Minute Workout",
    description: "Complete a 30-minute workout session",
    category: "fitness",
    difficulty: "medium",
    xpReward: 40,
    pointsReward: 25,
    estimatedTime: 30,
    createdBy: "system",
  },
  {
    id: "4",
    title: "Read a Book",
    description: "Read at least 20 pages of a book",
    category: "mindfulness",
    difficulty: "medium",
    xpReward: 25,
    pointsReward: 18,
    estimatedTime: 20,
    createdBy: "system",
  },
  {
    id: "5",
    title: "Drink 8 Glasses of Water",
    description: "Stay hydrated throughout the day",
    category: "fitness",
    difficulty: "easy",
    xpReward: 15,
    pointsReward: 5,
    estimatedTime: 0,
    createdBy: "system",
  },
  {
    id: "6",
    title: "Deep Work Session",
    description: "Complete a 1-hour focused work session without distractions",
    category: "productivity",
    difficulty: "hard",
    xpReward: 50,
    pointsReward: 35,
    estimatedTime: 60,
    createdBy: "system",
  },
  {
    id: "7",
    title: "Evening Reflection",
    description: "Reflect on your day and write down three things you're grateful for",
    category: "mindfulness",
    difficulty: "easy",
    xpReward: 20,
    pointsReward: 10,
    estimatedTime: 10,
    createdBy: "system",
  },
  {
    id: "8",
    title: "10,000 Steps",
    description: "Walk at least 10,000 steps today",
    category: "fitness",
    difficulty: "medium",
    xpReward: 35,
    pointsReward: 20,
    estimatedTime: 0,
    createdBy: "system",
  },
  {
    id: "9",
    title: "Inbox Zero",
    description: "Clear out your email inbox completely",
    category: "productivity",
    difficulty: "hard",
    xpReward: 45,
    pointsReward: 30,
    estimatedTime: 30,
    createdBy: "system",
  },
  {
    id: "10",
    title: "Breathing Exercise",
    description: "Perform a 5-minute deep breathing exercise",
    category: "mindfulness",
    difficulty: "easy",
    xpReward: 15,
    pointsReward: 7,
    estimatedTime: 5,
    createdBy: "system",
  },
  {
    id: "11",
    title: "Stretch Break",
    description: "Take a 10-minute stretching break to relax your muscles",
    category: "fitness",
    difficulty: "easy",
    xpReward: 20,
    pointsReward: 10,
    estimatedTime: 10,
    createdBy: "system",
  },
  {
    id: "12",
    title: "Declutter Workspace",
    description: "Organize and clean your desk or working area",
    category: "productivity",
    difficulty: "medium",
    xpReward: 30,
    pointsReward: 20,
    estimatedTime: 20,
    createdBy: "system",
  },
  {
    id: "13",
    title: "Mindful Eating",
    description: "Eat one meal without distractions, focusing fully on the food",
    category: "mindfulness",
    difficulty: "medium",
    xpReward: 25,
    pointsReward: 18,
    estimatedTime: 20,
    createdBy: "system",
  },
  {
    id: "14",
    title: "Quick Cardio Blast",
    description: "Complete a 15-minute high-intensity cardio session",
    category: "fitness",
    difficulty: "medium",
    xpReward: 30,
    pointsReward: 22,
    estimatedTime: 15,
    createdBy: "system",
  },
  {
    id: "15",
    title: "Pomodoro Session",
    description: "Complete four Pomodoro work sessions with short breaks",
    category: "productivity",
    difficulty: "hard",
    xpReward: 50,
    pointsReward: 40,
    estimatedTime: 100,
    createdBy: "system",
  },
  {
    id: "16",
    title: "Nature Walk",
    description: "Spend 20 minutes walking outdoors, preferably in nature",
    category: "mindfulness",
    difficulty: "easy",
    xpReward: 20,
    pointsReward: 12,
    estimatedTime: 20,
    createdBy: "system",
  },
  {
    id: "17",
    title: "Meal Prep",
    description: "Prepare healthy meals for the next 3 days",
    category: "productivity",
    difficulty: "hard",
    xpReward: 55,
    pointsReward: 45,
    estimatedTime: 90,
    createdBy: "system",
  },
  {
    id: "18",
    title: "Balance Workout",
    description: "Do a 20-minute session focused on balance and stability exercises",
    category: "fitness",
    difficulty: "medium",
    xpReward: 35,
    pointsReward: 22,
    estimatedTime: 20,
    createdBy: "system",
  },
  {
    id: "19",
    title: "Gratitude Journal",
    description: "Write down 5 things you're grateful for today",
    category: "mindfulness",
    difficulty: "easy",
    xpReward: 20,
    pointsReward: 10,
    estimatedTime: 10,
    createdBy: "system",
  },
];
