import type { Quest } from "./types";

export const mockQuests: Quest[] = [
  {
    id: "1",
    title: "Morning Meditation",
    description: "Start your day with a 10-minute meditation session",
    category: "mindfulness",
    difficulty: "easy",
    xpReward: 20,
    estimatedTime: 10,
  },
  {
    id: "2",
    title: "Plan Your Day",
    description: "Create a to-do list for today's tasks",
    category: "productivity",
    difficulty: "easy",
    xpReward: 15,
    estimatedTime: 5,
  },
  {
    id: "3",
    title: "30-Minute Workout",
    description: "Complete a 30-minute workout session",
    category: "fitness",
    difficulty: "medium",
    xpReward: 40,
    estimatedTime: 30,
  },
  {
    id: "4",
    title: "Read a Book",
    description: "Read at least 20 pages of a book",
    category: "mindfulness",
    difficulty: "medium",
    xpReward: 25,
    estimatedTime: 20,
  },
  {
    id: "5",
    title: "Drink 8 Glasses of Water",
    description: "Stay hydrated throughout the day",
    category: "fitness",
    difficulty: "easy",
    xpReward: 15,
    estimatedTime: 0,
  },
  {
    id: "6",
    title: "Deep Work Session",
    description: "Complete a 1-hour focused work session without distractions",
    category: "productivity",
    difficulty: "hard",
    xpReward: 50,
    estimatedTime: 60,
  },
  {
    id: "7",
    title: "Evening Reflection",
    description:
      "Reflect on your day and write down three things you're grateful for",
    category: "mindfulness",
    difficulty: "easy",
    xpReward: 20,
    estimatedTime: 10,
  },
  {
    id: "8",
    title: "10,000 Steps",
    description: "Walk at least 10,000 steps today",
    category: "fitness",
    difficulty: "medium",
    xpReward: 35,
    estimatedTime: 0,
  },
  {
    id: "9",
    title: "Inbox Zero",
    description: "Clear out your email inbox completely",
    category: "productivity",
    difficulty: "hard",
    xpReward: 45,
    estimatedTime: 30,
  },
];
